### ISSUE TITLE
Server doesn't download or start

### ISSUE THREAD

**Issue by Miskerest** [TrueOsiris/docker-vrising#20]
Using `docker-compose`: 

```
version: '3.3'
services:
  vrising:
    container_name: vrising
    image: trueosiris/vrising
    network_mode: bridge
    environment:
      - TZ=America/New_York
      - SERVERNAME=vrisingmisker
      - PUID=1001
      - PGID=1001
    volumes:
      - './server:/mnt/vrising/server:rw'
      - './data:/mnt/vrising/persistentdata:rw'
    ports:
      - '9876:9876/udp'
      - '9877:9877/udp'
 ```

```$ docker-compose up
vrising    | Setting timezone to America/New_York
vrising    |
vrising    | Current default time zone: 'America/New_York'
vrising    | Local time is now:      Fri Jun  3 11:12:20 EDT 2022.
vrising    | Universal Time is now:  Fri Jun  3 15:12:20 UTC 2022.
vrising    |
vrising    | usermod: user 'docker' does not exist
vrising    |
vrising    | Updating V-Rising Dedicated Server files...
vrising    |
```

No further output, neither the `server/` nor `data/` directory gets populated (so no conf files to edit)
