### ISSUE TITLE
Timeout only when password is set?

### ISSUE THREAD

**Issue by dev-kreg** [TrueOsiris/docker-vrising#48]
I am running the server through docker compose;

```
  vrising:
    container_name: vrising
    image: trueosiris/vrising
    environment:
      - TZ=America/Edmonton
      - SERVERNAME=****
    volumes:
      - './server:/mnt/vrising/server:rw'
      - './data:/mnt/vrising/persistentdata:rw'
    ports:
      - '9886:9886/udp'
      - '9887:9887/udp'
    restart: unless-stopped
    network_mode: bridge
```

The password I am setting inside `ServerHostSettings.json` however I am only able to connect with the line `"Password": "",` and when I enter anything inside the quotes and try to connect, it DOES ask for a password however after entering it I timeout. If I set the password to be blank again I can connect with no issue.
