### ISSUE TITLE
My server does't list in steam

### ISSUE THREAD

**Issue by vitorgdev** [TrueOsiris/docker-vrising#53]
![image](https://github.com/TrueOsiris/docker-vrising/assets/33029985/ea6aa907-342c-49e4-9109-4076d5c503f2)
                                                                                                                    
```
version: '3.3'
services:
  vrising:
    # build: . # Build from Dockerfile
    container_name: vrising
    image: trueosiris/vrising
    network_mode: bridge
    environment:
      - TZ=Brazil/Sao-Paulo
      - SERVERNAME=[BR] TERRA 81
    volumes:
      - './server:/mnt/vrising/server:rw'
      - './data:/mnt/vrising/persistentdata:rw'
    ports:
      - '25015:25015/udp'
      - '25016:25016/udp'

```

```
                                                                                                                             
   {
  "Name": "[BR] Terra 81 - Resetado 11/05",
  "Description": "",
  "Port": 25015,
  "QueryPort": 25016,
  "MaxConnectedUsers": 60,
  "MaxConnectedAdmins": 4,
  "ServerFps": 30,
  "SaveName": "world1",
  "Password": "",
  "Secure": true,
  "ListOnSteam": true,
  "ListOnEOS": true,
  "AutoSaveCount": 20,
  "AutoSaveInterval": 120,
  "CompressSaveFiles": true,
  "GameSettingsPreset": "",
  "GameDifficultyPreset": "",
  "AdminOnlyDebugEvents": true,
  "DisableDebugEvents": false,
  "API": {
    "Enabled": false
  },
  "Rcon": {
    "Enabled": false,
    "Port": 25575,
    "Password": ""
  }
}
```

My server is not listed on Steam.
