### ISSUE TITLE
runtime error when server closed

### ISSUE THREAD

**Issue by shiptux** [TrueOsiris/docker-vrising#94]
```
0128:fixme:winsock:server_ioctl_sock Unsupported ioctl 4004747b (device=4004 access=1 func=d1e method=3)                                                                                                                                                                                0128:fixme:winsock:WSAIoctl unsupported WS_IOCTL cmd (SIO_IDEAL_SEND_BACKLOG_QUERY)                                                                                                                                                                                                     Shutting down Server                                                                                                                                                                                                                                                                    X connection to :0.0 broken (explicit kill or server shutdown).                                                                                                                                                                                                                         Shutting down Server                                                                                                                                                                                                                                                                    (EE)/start.sh: line 8: pgrep: command not found                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 (EE) Backtrace:                                                                                                                                                                                                                                                                         (EE) 0: Xvfb (?+0x0) [0x557a4e9995b9]                                                                                                                                                                                                                                                   Could not find VRisingServer.exe pid. Assuming server is dead...                                                                                                                                                                                                                        (EE) 1: /lib/x86_64-linux-gnu/libc.so.6 (?+0x0) [0x7f54c2c42520]                                                                                                                                                                                                                        /start.sh: line 15: wineserver: command not found                                                                                                                                                                                                                                       /start.sh: line 16: sleep: command not found   
```

**Comment by TrueOsiris** [comment]
This is a wine error. Must have something to do with podman then.
I've just tested running & playing with the latest image and 1.1 hotfix 5 on my unraid server. (an old intel xeon)
Did you definitely pull the latest image or start from scratch? Or are you continuing an older version?

**Comment by redjax** [comment]
I am also getting this error when trying to connect to my server. This is my `compose.yml`:

```yaml
---
name: vrising-server

volumes:
  game_data: {}
  config_data: {}
  persistent_data: {}

networks:
  default:
    driver: bridge
    name: vrising_net

services:
  vrising-server:
    image: trueosiris/vrising:${VRISING_SERVER_CONTAINER_IMG_VER:-latest}
    container_name: vrising-server
    restart: unless-stopped
    ports:
      - ${VIRISING_SERVER_PORT:-9876}:9876/udp
      - ${VRISING_SERVER_QUERY_PORT:-9877}:9877/udp
    environment:
      TZ: ${TZ:-Etc/UTC}
      SERVERNAME: ${VRISING_SERVER_NAME:-"Dockerized VRising Server"}
      WORLDNAME: ${VRISING_SERVER_WORLDNAME:-world1}
      GAMEPORT: 9876
      QUERYPORT: 9877
      LOGDAYS: ${VRISING_SERVER_LOGDAYS:-30}
    volumes:
      - ${VRISING_SERVER_DATA_DIR:-game_data}:/mnt/vrising/server
      - ${VRISING_SERVER_CONFIG_DIR:-config_data}:/mnt/vrising/server/VRisingServer_Data
      - ${VRISING_SERVER_PERSIST_DIR:-persistent_data}:/mnt/vrising/persistentdata

      ##
      # Comment out/remove VRISING_SERVER_GAME_SETTINGS_FILE and VRISING_SERVER_GAME_HOST_SETTINGS_FILE
      # if using a host mount (local directory).
      ##

      ## Mount ServerGameSettings.json from host
      # - ${VRISING_SERVER_GAME_SETTINGS_FILE:-./configs/ServerGameSettings.json}:/mnt/vrising/server/VRisingServer_Data/StreamingAssets/Settings/ServerGameSettings.json
      ## Mount ServerHostSettings.json from host
      # - ${VRISING_SERVER_HOST_SETTINGS_FILE:-./configs/ServerHostSettings.json}:/mnt/vrising/server/VRisingServer_Data/StreamingAssets/Settings/ServerHostSettings.json

    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: vrising-server_watchtower
    restart: unless-stopped
    environment:
      ## Remove old images after updating
      WATCHTOWER_CLEANUP: "true"
      ## Only update containers with the `com.centurylinklabs.watchtower.enable=true` label
      WATCHTOWER_LABEL_ENABLE: "true"
      ## Check for updates every 300 seconds (5 minutes)
      WATCHTOWER_POLL_INTERVAL: 300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

```

I'm bringing the server up, letting it install, bringing it down, and copying the following `ServerGameSettings.json` and `ServerHostSettings.json` into the persist/Settings directory:

```json
{
  "GameDifficulty": "Normal",
  "GameModeType": "PvE",
  "CastleDamageMode": "Never",
  "SiegeWeaponHealth": "Normal",
  "PlayerDamageMode": "Always",
  "CastleHeartDamageMode": "CanBeDestroyedByPlayers",
  "PvPProtectionMode": "Medium",
  "DeathContainerPermission": "ClanMembers",
  "RelicSpawnType": "Plentiful",
  "SoulShard_DurabilityLossRate": 0.5,
  "CanLootEnemyContainers": true,
  "BloodBoundEquipment": true,
  "TeleportBoundItems": false,
  "BatBoundItems": false,
  "BatBoundShards": false,
  "AllowGlobalChat": true,
  "AllWaypointsUnlocked": true,
  "FreeCastleRaid": false,
  "FreeCastleClaim": false,
  "FreeCastleDestroy": false,
  "InactivityKillEnabled": false,
  "InactivityKillTimeMin": 3600,
  "InactivityKillTimeMax": 604800,
  "InactivityKillSafeTimeAddition": 172800,
  "InactivityKillTimerMaxItemLevel": 84,
  "StartingProgressionLevel": 0,
  "DisableDisconnectedDeadEnabled": true,
  "DisableDisconnectedDeadTimer": 60,
  "DisconnectedSunImmunityTime": 300.0,
  "InventoryStacksModifier": 2.0,
  "DropTableModifier_General": 1.5,
  "DropTableModifier_StygianShards": 1.5,
  "DropTableModifier_Missions": 1.5,
  "MaterialYieldModifier_Global": 1.75,
  "BloodEssenceYieldModifier": 1.75,
  "JournalVBloodSourceUnitMaxDistance": 50.0,
  "PvPVampireRespawnModifier": 1.0,
  "CastleMinimumDistanceInFloors": 0,
  "ClanSize": 20,
  "BloodDrainModifier": 0.5,
  "DurabilityDrainModifier": 0.5,
  "GarlicAreaStrengthModifier": 0.5,
  "HolyAreaStrengthModifier": 0.5,
  "SilverStrengthModifier": 0.5,
  "SunDamageModifier": 0.5,
  "CastleDecayRateModifier": 0,
  "CastleBloodEssenceDrainModifier": 0.5,
  "CastleSiegeTimer": 420.0,
  "CastleUnderAttackTimer": 60.0,
  "CastleRaidTimer": 600.0,
  "CastleRaidProtectionTime": 1800.0,
  "CastleExposedFreeClaimTimer": 300.0,
  "CastleRelocationCooldown": 0,
  "CastleRelocationEnabled": true,
  "AnnounceSiegeWeaponSpawn": true,
  "ShowSiegeWeaponMapIcon": true,
  "BuildCostModifier": 0.5,
  "RecipeCostModifier": 0.5,
  "CraftRateModifier": 1.5,
  "ResearchCostModifier": 0.5,
  "RefinementCostModifier": 0.5,
  "RefinementRateModifier": 1.5,
  "ResearchTimeModifier": 1.5,
  "DismantleResourceModifier": 1.0,
  "ServantConvertRateModifier": 3.0,
  "RepairCostModifier": 0.5,
  "Death_DurabilityFactorLoss": 0.125,
  "Death_DurabilityLossFactorAsResources": 1.0,
  "StarterEquipmentId": -1502721803,
  "StarterResourcesId": 0,
  "VBloodUnitSettings": [
    {
      "UnitId": -1905691330,
      "UnitLevel": 16,
      "DefaultUnlocked": true
    }
  ],
  "UnlockedAchievements": [],
  "UnlockedResearchs": [],
  "GameTimeModifiers": {
    "DayDurationInSeconds": 1080.0,
    "DayStartHour": 9,
    "DayStartMinute": 0,
    "DayEndHour": 18,
    "DayEndMinute": 0,
    "BloodMoonFrequency_Min": 5,
    "BloodMoonFrequency_Max": 10,
    "BloodMoonBuff": 0.8
  },
  "VampireStatModifiers": {
    "MaxHealthModifier": 1.0,
    "PhysicalPowerModifier": 1.2,
    "SpellPowerModifier": 1.2,
    "ResourcePowerModifier": 1.2,
    "SiegePowerModifier": 1.0,
    "DamageReceivedModifier": 0.8,
    "ReviveCancelDelay": 5.0
  },
  "UnitStatModifiers_Global": {
    "MaxHealthModifier": 1.0,
    "PowerModifier": 1.0,
    "LevelIncrease": 0
  },
  "UnitStatModifiers_VBlood": {
    "MaxHealthModifier": 1.0,
    "PowerModifier": 1.0,
    "LevelIncrease": 0
  },
  "EquipmentStatModifiers_Global": {
    "MaxHealthModifier": 1.0,
    "ResourceYieldModifier": 1.2,
    "PhysicalPowerModifier": 1.2,
    "SpellPowerModifier": 1.0,
    "SiegePowerModifier": 1.0,
    "MovementSpeedModifier": 1.0
  },
  "CastleStatModifiers_Global": {
    "TickPeriod": 600,
    "SafetyBoxLimit": 255,
    "EyeStructuresLimit": 255,
    "TombLimit": 20,
    "VerminNestLimit": 15,
    "PrisonCellLimit": 40,
    "HeartLimits": {
      "Level1": {
        "FloorLimit": 70,
        "ServantLimit": 1,
        "HeightLimit": 3
      },
      "Level2": {
        "FloorLimit": 170,
        "ServantLimit": 5,
        "HeightLimit": 3
      },
      "Level3": {
        "FloorLimit": 270,
        "ServantLimit": 7,
        "HeightLimit": 3
      },
      "Level4": {
        "FloorLimit": 390,
        "ServantLimit": 12,
        "HeightLimit": 3
      },
      "Level5": {
        "FloorLimit": 580,
        "ServantLimit": 20,
        "HeightLimit": 3
      }
    },
    "CastleHeartLimitType": "User",
    "CastleLimit": 2,
    "NetherGateLimit": 1,
    "ThroneOfDarknessLimit": 1,
    "ArenaStationLimit": 5,
    "RoutingStationLimit": 10
  },
  "PlayerInteractionSettings": {
    "TimeZone": "Local",
    "VSPlayerWeekdayTime": {
      "StartHour": 20,
      "StartMinute": 0,
      "EndHour": 22,
      "EndMinute": 0
    },
    "VSPlayerWeekendTime": {
      "StartHour": 20,
      "StartMinute": 0,
      "EndHour": 22,
      "EndMinute": 0
    },
    "VSCastleWeekdayTime": {
      "StartHour": 20,
      "StartMinute": 0,
      "EndHour": 22,
      "EndMinute": 0
    },
    "VSCastleWeekendTime": {
      "StartHour": 20,
      "StartMinute": 0,
      "EndHour": 22,
      "EndMinute": 0
    }
  },
  "TraderModifiers": {
    "StockModifier": 2.0,
    "PriceModifier": 0.75,
    "RestockTimerModifier": 0.5
  },
  "WarEventGameSettings": {
    "Interval": 1,
    "MajorDuration": 1,
    "MinorDuration": 1,
    "WeekdayTime": {
      "StartHour": 0,
      "StartMinute": 0,
      "EndHour": 23,
      "EndMinute": 59
    },
    "WeekendTime": {
      "StartHour": 0,
      "StartMinute": 0,
      "EndHour": 23,
      "EndMinute": 59
    },
    "ScalingPlayers1": {
      "PointsModifier": 1.0,
      "DropModifier": 1.0
    },
    "ScalingPlayers2": {
      "PointsModifier": 0.5,
      "DropModifier": 0.5
    },
    "ScalingPlayers3": {
      "PointsModifier": 0.25,
      "DropModifier": 0.25
    },
    "ScalingPlayers4": {
      "PointsModifier": 0.25,
      "DropModifier": 0.25
    }
  }
}
```

```json
{
  "Name": "Easy Mode",
  "Description": "Server settings have been tweaked, drops are more rewarding & abundant, you're a bit stronger, you can build more, and you start with some boss powers.",
  "Port": 9876,
  "QueryPort": 9877,
  "MaxConnectedUsers": 40,
  "MaxConnectedAdmins": 4,
  "ServerFps": 30,
  "SaveName": "ezmode",
  "Password": null,
  "Secure": true,
  "ListOnSteam": true,
  "ListOnEOS": true,
  "AutoSaveCount": 20,
  "AutoSaveInterval": 120,
  "CompressSaveFiles": true,
  "GameSettingsPreset": "",
  "GameDifficultyPreset": "",
  "AdminOnlyDebugEvents": true,
  "DisableDebugEvents": false,
  "API": {
    "Enabled": false
  },
  "Rcon": {
    "Enabled": false,
    "Port": 25575,
    "Password": ""
  }
}
```

This is the `.env` file I'm using to apply parameters:

```plaintext
## Default: Etc/UTC
TZ=

## Default: latest
VRISING_SERVER_CONTAINER_IMG_VER=
## Default: 9876
VIRISING_SERVER_PORT=
## Default: 9877
VRISING_SERVER_QUERY_PORT=
## Default: "Dockerized VRising Server"
VRISING_SERVER_NAME=
## Default: world1
VRISING_SERVER_WORLDNAME=
## Default: 30
VRISING_SERVER_LOGDAYS=
## Default: main
VRISING_SERVER_BRANCH=
## Default: (named volume) game_data
VRISING_SERVER_DATA_DIR=
## Default: (named volume) config_data
VRISING_SERVER_CONFIG_DIR=
## Default: (named volume) persistent_data
VRISING_SERVER_PERSIST_DIR=./vrising/persist


```

When I bring the server up, things seem to load ok, but when trying to connect from my game I see these errors in the logs:

```shell
vrising-server  | Triggering AutoSave 1!
vrising-server  | PersistenceV2 - Finished Saving to 'Z:\mnt\vrising\persistentdata\Saves\v4\ezmode\AutoSave_1.save.gz'. Total Persistent ChunkCount 2673. Total Save Size: 7066606 Total Uncompressed Save Size: 33505523 Bytes System Data Size: 1828 Bytes World Data Size: 4194313 Bytes Header Data Size: 819702 Bytes, (Job 0 ArchetypeCount 17, ChunkCount 2043), (Job 1 ArchetypeCount 123, ChunkCount 630), (Job 2 ArchetypeCount 0, ChunkCount 0), (Job 3 ArchetypeCount 0, ChunkCount 0)
vrising-server  | 0150:fixme:winsock:server_ioctl_sock Unsupported ioctl 4004747b (device=4004 access=1 func=d1e method=3)
vrising-server  | 0150:fixme:winsock:WSAIoctl unsupported WS_IOCTL cmd (SIO_IDEAL_SEND_BACKLOG_QUERY)
```
