### ISSUE TITLE
Can't seem to be able to configure the server

### ISSUE THREAD

**Issue by rodbeck** [TrueOsiris/docker-vrising#98]
Hi,

Fist of all, thanks a lot for this work.

I tried to launch the server with a former save:

compose.yaml:

```
services:
  vrising:
    image: trueosiris/vrising
    environment:
      - TZ=Europe/Paris
      - SERVERNAME=vrising
      - WORLDNAME=world2
    volumes:
      - type: bind
        source: /opt/stack/vrising/server
        target: /mnt/vrising/server
        bind:
          create_host_path: true
      - type: bind
        source: /opt/stack/vrising/persistentdata
        target: /mnt/vrising/persistentdata
        bind:
          create_host_path: true
    ports:
      - '9876:9876/udp'
      - '9877:9877/udp'
    restart: unless-stopped
    network_mode: bridge
```

ServerHostSettings.json:

```
{^M
  "Name": "V Rising Server",^M
  "Description": "",^M
  "Port": 9876,^M
  "QueryPort": 9877,^M
  "MaxConnectedUsers": 40,^M
  "MaxConnectedAdmins": 4,^M
  "ServerFps": 30,^M
  "SaveName": "world2",^M
  "Password": "",^M
  "Secure": true,^M
  "ListOnSteam": false,^M
  "ListOnEOS": false,^M
  "SaveName": world2,
  "AutoSaveCount": 20,^M
  "AutoSaveInterval": 120,^M
  "CompressSaveFiles": true,^M
  "GameSettingsPreset": "StandardPvE",^M
  "GameDifficultyPreset": "Difficulty_Normal",^M
  "AdminOnlyDebugEvents": true,^M
  "DisableDebugEvents": false,^M
  "API": {^M
    "Enabled": false^M
  },^M
  "Rcon": {^M
    "Enabled": false,^M
    "Port": 25575,^M
    "Password": ""^M
  }^M
}
```

I initially tried to replace the save game from "world1" by my save game, but it was overwritten.
I therefore created a "world2" folder and added my save, then configured it to be the world to launch, both in the compose file and the settings file to no avail.
According to "docker compose logs" the server still seeks files in world1.
Also, it seems that the host folders are no longer updated, as I tried to start from scratch with 'docker compose down' and rename the folders in /opt/stack/vrising/server and they are not recreated.

Can you please put me on the right track? It seems that I misunderstood how to configure the docker container in the compose file.

Thanks.
